version: "3.8"
services:
  dev:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
    volumes:
      - type: bind
        source: ./server
        target: /usr/src/app/server
    ports:
      - "8080:8080"
volumes:
  nodemodules:
