version: "3.8"
services:
  dev:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./server
        target: ${WORKDIR}/server
      - type: bind
        source: ${T_PATH}
        target: ${WORKDIR}/stock
volumes:
  nodemodules:
